/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author chira
 */
public class Bankview extends javax.swing.JFrame {
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
    /**
     * Creates new form Bankview
     */
    public Bankview() {
        initComponents();
         con=databaseConnection.connection();
        showBankac();
    }
 public void showBankac(){
        try
        {
            stmt=con.createStatement();
            if(actype.getSelectedItem().equals("All"))
            {
                
            
            String query="SELECT * FROM bank";
            ResultSet re=stmt.executeQuery(query);
            banktable.setModel(DbUtils.resultSetToTableModel(re));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        actype = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        banktable = new javax.swing.JTable();
        AddEdit = new javax.swing.JButton();
        SamurdhiAccount = new javax.swing.JButton();
        Menu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Bank Account");

        actype.setBackground(new java.awt.Color(102, 255, 102));
        actype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        actype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "All", "Members' shares", "Members' deposits", "Group deposits", "Diriya Maatha", "Kekulu", "Sisureka", "Compulsory savings" }));
        actype.setSelectedIndex(1);
        actype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actypeActionPerformed(evt);
            }
        });

        banktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(banktable);

        AddEdit.setBackground(new java.awt.Color(153, 153, 153));
        AddEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddEdit.setText("Add/Edit");
        AddEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditActionPerformed(evt);
            }
        });

        SamurdhiAccount.setBackground(new java.awt.Color(153, 153, 153));
        SamurdhiAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SamurdhiAccount.setText("Fund Transfer");
        SamurdhiAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamurdhiAccountActionPerformed(evt);
            }
        });

        Menu1.setBackground(new java.awt.Color(153, 153, 153));
        Menu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Menu1.setText("Menu");
        Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AddEdit)
                        .addGap(540, 540, 540))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(actype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(475, 475, 475))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(SamurdhiAccount)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(853, Short.MAX_VALUE)
                    .addComponent(Menu1)
                    .addGap(247, 247, 247)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(actype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(AddEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(SamurdhiAccount)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(588, Short.MAX_VALUE)
                    .addComponent(Menu1)
                    .addGap(82, 82, 82)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actypeActionPerformed
        // TODO add your handling code here:
        try{
            stmt=con.createStatement();
            if(actype.getSelectedItem().equals("All"))
            {
                String query="SELECT * FROM bank";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }

            if(actype.getSelectedItem().equals("Members' shares"))
            {
                String query="SELECT * FROM bank WHERE actype='Members' shares'";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }

            if(actype.getSelectedItem().equals("Members' deposits"))
            {
                String query="SELECT * FROM bank WHERE actype='Members' deposits'";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }

            if(actype.getSelectedItem().equals("Group deposits"))
            {
                String query="SELECT * FROM bank WHERE actype='Group deposits'";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }
            
            if(actype.getSelectedItem().equals("Diriya Maatha"))
            {
                String query="SELECT * FROM bank WHERE actype='Diriya Maatha'";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }
            
            if(actype.getSelectedItem().equals("Kekulu"))
            {
                String query="SELECT * FROM bank WHERE actype='Kekulu'";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }
            
            if(actype.getSelectedItem().equals("Sisureka"))
            {
                String query="SELECT * FROM bank WHERE actype='Sisureka'";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }
            
            if(actype.getSelectedItem().equals("Compulsory savings"))
            {
                String query="SELECT * FROM bank WHERE actype='Compulsory savings'";
                ResultSet re=stmt.executeQuery(query);
                banktable.setModel(DbUtils.resultSetToTableModel(re));
            }
             
            
        } 
          catch(Exception e){
            System.out.println(e);
          }
    }//GEN-LAST:event_actypeActionPerformed

    private void AddEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEditActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        BankAccount view=new BankAccount();
        view.setVisible(true);

    }//GEN-LAST:event_AddEditActionPerformed

    private void SamurdhiAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamurdhiAccountActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        FundTransfer view=new FundTransfer();
        view.setVisible(true);

    }//GEN-LAST:event_SamurdhiAccountActionPerformed

    private void Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        Menu view=new Menu();
        view.setVisible(true);
    }//GEN-LAST:event_Menu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bankview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bankview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bankview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bankview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bankview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEdit;
    private javax.swing.JButton Menu1;
    private javax.swing.JButton SamurdhiAccount;
    private javax.swing.JComboBox<String> actype;
    private javax.swing.JTable banktable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
