/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chira
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Beneficiaries = new javax.swing.JButton();
        Loanprograms = new javax.swing.JButton();
        Bank = new javax.swing.JButton();
        Socialprotection = new javax.swing.JButton();
        Summary = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        Beneficiaries.setBackground(new java.awt.Color(153, 153, 153));
        Beneficiaries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Beneficiaries.setForeground(new java.awt.Color(255, 51, 51));
        Beneficiaries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/benefi1.jpg"))); // NOI18N
        Beneficiaries.setText("Beneficiaries");
        Beneficiaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeneficiariesActionPerformed(evt);
            }
        });

        Loanprograms.setBackground(new java.awt.Color(153, 153, 153));
        Loanprograms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Loanprograms.setForeground(new java.awt.Color(255, 51, 51));
        Loanprograms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loan1.jpg"))); // NOI18N
        Loanprograms.setText("Loan Programs");
        Loanprograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanprogramsActionPerformed(evt);
            }
        });

        Bank.setBackground(new java.awt.Color(153, 153, 153));
        Bank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bank.setForeground(new java.awt.Color(255, 51, 51));
        Bank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank2.jpg"))); // NOI18N
        Bank.setText("Bank Accounts");
        Bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankActionPerformed(evt);
            }
        });

        Socialprotection.setBackground(new java.awt.Color(153, 153, 153));
        Socialprotection.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Socialprotection.setForeground(new java.awt.Color(255, 51, 51));
        Socialprotection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social protection2.jpg"))); // NOI18N
        Socialprotection.setText("Social Protection Fund");
        Socialprotection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SocialprotectionActionPerformed(evt);
            }
        });

        Summary.setBackground(new java.awt.Color(153, 153, 153));
        Summary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Summary.setForeground(new java.awt.Color(255, 51, 51));
        Summary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/summary1.jpg"))); // NOI18N
        Summary.setText("Summary");
        Summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.jpg"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Beneficiaries, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Loanprograms, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bank, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Socialprotection, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Summary, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(456, 456, 456))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(Beneficiaries)
                .addGap(31, 31, 31)
                .addComponent(Loanprograms, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Bank, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Socialprotection, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Summary, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void BeneficiariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeneficiariesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        BenefiView view=new BenefiView();
        view.setVisible(true);
    }//GEN-LAST:event_BeneficiariesActionPerformed

    private void LoanprogramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanprogramsActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        Loanview view=new Loanview();
        view.setVisible(true);
    }//GEN-LAST:event_LoanprogramsActionPerformed

    private void BankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        Bankview view=new Bankview();
        view.setVisible(true);
    }//GEN-LAST:event_BankActionPerformed

    private void SocialprotectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SocialprotectionActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        Socialview view=new Socialview();
        view.setVisible(true);
    }//GEN-LAST:event_SocialprotectionActionPerformed

    private void SummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryActionPerformed
        // TODO add your handling code here:
                 setVisible(false);
        Summary view=new Summary();
        view.setVisible(true);
    }//GEN-LAST:event_SummaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bank;
    private javax.swing.JButton Beneficiaries;
    private javax.swing.JButton Loanprograms;
    private javax.swing.JButton Socialprotection;
    private javax.swing.JButton Summary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
